name: Lulu Manual Post
on: { workflow_dispatch: {} }
jobs:
  now:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - name: Force one-time post
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          FORCE_NOW: "1"
        run: python .github/scripts/lulu_post.py
